Select
    cast(vendor_id as string) as vendor_id,
    pickup_datetime,
    dropoff_datetime,
    passenger_count,
    trip_distance,
    cast(rate_code as string) as rate_code,
    store_and_fwd_flag,
    cast(payment_type as string) as payment_type,
    fare_amount,
    extra,
    mta_tax,
    tip_amount,
    tolls_amount,
    imp_surcharge,
    total_amount,
    pickup_location_id,
    dropoff_location_id,
    'yellow' as taxi_type,
    cast(null as numeric) as ehail_fee,
    cast(null as string) as trip_type_green,
    cast(null as numeric) as distance_between_service,
    cast(null as int64) as time_between_service
from {{ source('tlc', 'tlc_yellow_trips_2022')}}